[appenders.console]
kind = "console"
encoder = { pattern = "{h({d(%Y-%m-%d %H:%M:%S.%f)(local):.23})} | {h({l}):>5} | {M}:{L} - {m}{n}" }

[appenders.ui_log]
kind = "ui_logs"
max_size = 10240

[loggers.lol_helper]
level = "INFO"
appenders = ["console, ui_log"]
